version: "3"
services:
  db:
    container_name: postgres
    image: postgres:14.5
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  next:
    container_name: next-front
    build:
      context: .
      dockerfile: docker/next/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
    working_dir: /front
    stdin_open: true
    tty: true
    command: npm run dev

  go:
    container_name: go-back
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./back:/back
    env_file: ./.env
    tty: true
    command: go run main.go

volumes:
  postgres: