version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  next:
    container_name: next-front
    build:
      context: .
      dockerfile: docker/next/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
    environment:
      - API_URL=${API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
    working_dir: /front
    stdin_open: true
    tty: true
    depends_on:
      - go
    command: npm run dev

  go:
    container_name: go-back
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./back:/back
    env_file: ./.env
    ports:
      - "8080:8080"
    tty: true
    command: go run main.go

volumes:
  postgres_data:
